### PR TITLE
Fix `pre-commit` autoupdate problems.

### LINKED ISSUE #25: Problem with pre-commit auto update
I merged #23, and ran it manually. The run failed like this:

https://github.com/googlefonts/fontra-glyphs/actions/runs/8016379275/workflow

I'm not sure I understand. The updated black may have caused a file to be reformatted, which somehow prevents the rest of the action to run. This feels a bit like chicken and egg.

@fabiocaccamo, can you investigate? In the worst case I'll have to do a manual update of the pre-commit dependencies first, but that feels like it's defeating the purpose.

### PR DESCRIPTION
**Pull request by fabiocaccamo**
Fix #25 problems.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
The CI fails, but the error seems to be unrelated to the changes.

**Comment by justvanrossum** [comment]
This does not really fix the problem. Because the action (to create a PR) will fail again in the same way when black changes the formatting rules.

**Comment by justvanrossum** [comment]
Sorry about the test failure, that's indeed unrelated. I will fix that.

**Comment by justvanrossum** [comment]
Test failure fixed here: https://github.com/googlefonts/fontra-glyphs/commit/7506a7d8d4da76512c79f9c36d958b11ce6d37b3

**Comment by fabiocaccamo** [comment]
> This does not really fix the problem. Because the action (to create a PR) will fail again in the same way when black changes the formatting rules.

I don't think that we can avoid this. So yes, it will fail again in the future, but not always, just a few times.

**Comment by justvanrossum** [comment]
But that defies the whole purpose. The action should only update the dependencies, but not _run_ pre-commit.

**Comment by fabiocaccamo** [comment]
The action doesn't run `pre-commit`, it just updates the dependencies, then it's the CI that runs `pre-commit` using the updated `pre-commit` hooks dependencies at it fails.

**Comment by fabiocaccamo** [comment]
I updated an issue on the action repository: https://github.com/browniebroke/pre-commit-autoupdate-action/issues/2

**Comment by fabiocaccamo** [comment]
Now it should be ok.

**Comment by justvanrossum** [comment]
Thanks! Can you please revert https://github.com/googlefonts/fontra-glyphs/pull/27/commits/ae8940ac38a0bbad805788ab8ac8a19a9e787f70, so we can test it for real?

**Comment by justvanrossum** [comment]
And https://github.com/googlefonts/fontra-glyphs/pull/27/commits/4b4be19de7af763091173e6db11e509cc1501b7f, actually.

**Comment by justvanrossum** [comment]
Or a new PR with just your last commit if that's easier.

**Comment by justvanrossum** [comment]
Thanks! I'm afraid I will have to merge to test...

**Pull request merged**
